-- ═══════════════════════════════════════════════════════════════════════
-- Periodes de vente — « remise a zero » non destructive + calendrier
--
-- Besoin : a la fin d'une vente privee, l'admin veut remettre les compteurs
-- du tableau de bord a zero pour l'evenement suivant, SANS rien supprimer, et
-- pouvoir retrouver chaque periode passee.
--
-- Modele : une table `periodes`. Il y a toujours UNE periode ouverte (fin is
-- null) = la periode « en cours ». Une vente appartient a la periode dont
-- l'intervalle [debut, fin) contient sa date_vente — on n'ajoute donc AUCUNE
-- colonne aux ventes, et enregistrer_vente() reste inchangee.
--
-- « Cloturer » = fermer la periode ouverte (fin = now) et en ouvrir une neuve.
-- Les ventes restent toutes en base : seuls les COMPTEURS du dashboard, bornes
-- a la periode active, repartent a zero. Les dettes (reste_a_payer) restent
-- GLOBALES (l'argent du ne disparait pas a la cloture — choix proprietaire).
--
-- Conventions : security definer + search_path = '' + garde prive.est_admin().
-- ═══════════════════════════════════════════════════════════════════════

create table if not exists public.periodes (
  id      bigint generated by default as identity primary key,
  nom     text        not null default 'Période',
  debut   timestamptz not null default now(),
  fin     timestamptz,                    -- null = periode ouverte (active)
  cree_le timestamptz not null default now()
);

alter table public.periodes enable row level security;

-- Lecture pour tout connecte (le calendrier lit la table cote client). Les
-- ecritures passent uniquement par les RPC security definer ci-dessous.
drop policy if exists "periodes: lecture connectes" on public.periodes;
create policy "periodes: lecture connectes"
  on public.periodes for select to authenticated
  using (prive.est_connecte());

-- Grants (piege projet : sans ca, la cle secrete et les connectes se prennent
-- un permission denied sur une table neuve).
grant select on public.periodes to authenticated;
grant all    on public.periodes to service_role;

-- Amorce : une premiere periode ouverte couvrant toutes les ventes existantes.
insert into public.periodes (nom, debut, fin)
select 'Période initiale',
       coalesce((select min(date_vente) from public.ventes), now()),
       null
where not exists (select 1 from public.periodes);


-- ─── Cloture : ferme la periode active, en ouvre une neuve ──────────────
create or replace function public.cloturer_periode(p_nom text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_active     record;
  v_maintenant timestamptz := now();
  v_ca         numeric := 0;
  v_nb         integer := 0;
begin
  if not prive.est_admin() then
    raise exception 'Reserve a l''administrateur';
  end if;

  -- Verrou sur la periode ouverte (serialise deux clotures concurrentes).
  select * into v_active from public.periodes where fin is null order by debut desc limit 1 for update;

  if found then
    update public.periodes
       set fin = v_maintenant,
           nom = coalesce(nullif(btrim(p_nom), ''), nom)
     where id = v_active.id;

    select coalesce(sum(total), 0), count(*) into v_ca, v_nb
      from public.ventes
     where annulee = false
       and date_vente >= v_active.debut
       and date_vente <  v_maintenant;
  end if;

  insert into public.periodes (nom, debut, fin)
  values ('Période en cours', v_maintenant, null);

  return jsonb_build_object(
    'periode_cloturee', v_active.id,
    'ca', v_ca,
    'nb_ventes', v_nb,
    'fin', v_maintenant
  );
end;
$$;

revoke execute on function public.cloturer_periode(text) from public, anon;
grant execute on function public.cloturer_periode(text) to authenticated;


-- ─── Renommer une periode (etiquette du calendrier) ────────────────────
create or replace function public.renommer_periode(p_id bigint, p_nom text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not prive.est_admin() then
    raise exception 'Reserve a l''administrateur';
  end if;
  if p_nom is null or btrim(p_nom) = '' then
    raise exception 'Le nom est obligatoire';
  end if;
  update public.periodes set nom = btrim(p_nom) where id = p_id;
end;
$$;

revoke execute on function public.renommer_periode(bigint, text) from public, anon;
grant execute on function public.renommer_periode(bigint, text) to authenticated;


-- ─── Tableau de bord borne a la periode active ─────────────────────────
-- Les compteurs (CA, produits vendus, classement, produits par CA, par mode)
-- ne comptent QUE la periode en cours -> ils repartent a zero apres cloture.
-- Restent GLOBAUX : stock_restant (etat courant) et paiements_en_attente
-- (les dettes restent dues). Le comparatif reste calendaire (mois vs mois).
create or replace function public.tableau_de_bord_admin()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_result jsonb;
  v_tz constant text := 'Africa/Douala';
  v_debut_mois      timestamp := date_trunc('month', (now() at time zone v_tz));
  v_debut_mois_prec timestamp := date_trunc('month', (now() at time zone v_tz)) - interval '1 month';
  v_periode record;
  v_depuis  timestamptz;
begin
  if not prive.est_admin() then
    raise exception 'Acces reserve a l''administratrice';
  end if;

  select id, nom, debut into v_periode
    from public.periodes where fin is null order by debut desc limit 1;
  v_depuis := coalesce(v_periode.debut, '-infinity'::timestamptz);

  select jsonb_build_object(

    'periode', jsonb_build_object(
      'id', v_periode.id,
      'nom', coalesce(v_periode.nom, 'Période en cours'),
      'debut', v_periode.debut
    ),

    'stats', jsonb_build_object(
      'total_ventes', coalesce(
        (select sum(total) from public.ventes
          where annulee = false and date_vente >= v_depuis), 0),
      'produits_vendus', coalesce(
        (select sum(vp.quantite)
           from public.vente_produits vp
           join public.ventes v on v.id = vp.vente_id
          where v.annulee = false and v.date_vente >= v_depuis), 0),
      'stock_restant', coalesce(
        (select sum(stock_restant) from public.produits), 0),
      'paiements_en_attente', coalesce(
        (select sum(reste_a_payer) from public.ventes where annulee = false), 0)
    ),

    'comparatif', jsonb_build_object(
      'ca_mois', coalesce((
        select sum(total) from public.ventes
         where annulee = false
           and (date_vente at time zone v_tz) >= v_debut_mois), 0),
      'nb_mois', (
        select count(*) from public.ventes
         where annulee = false
           and (date_vente at time zone v_tz) >= v_debut_mois),
      'ca_mois_prec', coalesce((
        select sum(total) from public.ventes
         where annulee = false
           and (date_vente at time zone v_tz) >= v_debut_mois_prec
           and (date_vente at time zone v_tz) <  v_debut_mois), 0),
      'nb_mois_prec', (
        select count(*) from public.ventes
         where annulee = false
           and (date_vente at time zone v_tz) >= v_debut_mois_prec
           and (date_vente at time zone v_tz) <  v_debut_mois)
    ),

    'ca_par_mode', coalesce((
      select jsonb_agg(m order by m.total desc)
      from (
        select coalesce(nullif(btrim(p.mode), ''), 'cash') as mode,
               sum(p.montant) as total
          from public.paiements p
          join public.ventes v on v.id = p.vente_id
         where v.annulee = false and v.date_vente >= v_depuis
         group by 1
      ) m
    ), '[]'::jsonb),

    'produits_ca', coalesce((
      select jsonb_agg(pc order by pc.ca desc)
      from (
        select pr.nom,
               sum(vp.quantite) as quantite,
               sum(vp.prix_unitaire * vp.quantite) as ca
          from public.vente_produits vp
          join public.ventes v    on v.id = vp.vente_id
          join public.produits pr on pr.id = vp.produit_id
         where v.annulee = false and v.date_vente >= v_depuis
         group by pr.id, pr.nom
         order by ca desc
         limit 5
      ) pc
    ), '[]'::jsonb),

    'ventes_recentes', coalesce((
      select jsonb_agg(r order by r.date_vente desc)
      from (
        select v.id,
               v.date_vente,
               coalesce(c.nom, 'Inconnue') as cliente_nom,
               coalesce(u.nom, 'Inconnue') as vendeuse_nom,
               v.total,
               v.statut_paiement
          from public.ventes v
          left join public.clientes c    on c.id = v.cliente_id
          left join public.utilisateurs u on u.id = v.vendeuse_id
         where v.annulee = false
         order by v.date_vente desc
         limit 5
      ) r
    ), '[]'::jsonb),

    'top_vendeuses', coalesce((
      select jsonb_agg(t order by t.total desc)
      from (
        select u.id,
               u.nom,
               count(v.id)               as nb,
               coalesce(sum(v.total), 0) as total
          from public.ventes v
          join public.utilisateurs u on u.id = v.vendeuse_id
         where v.annulee = false and v.date_vente >= v_depuis
         group by u.id, u.nom
         order by total desc
         limit 3
      ) t
    ), '[]'::jsonb)

  ) into v_result;

  return v_result;
end;
$$;

revoke execute on function public.tableau_de_bord_admin() from public, anon;
grant execute on function public.tableau_de_bord_admin() to authenticated;
