-- ═══════════════════════════════════════════════════════════════════════
-- Objectifs mensuels par vendeuse
--
-- Une ligne = l'objectif de CA d'une vendeuse pour un mois donne (periode =
-- premier jour du mois). L'admin fixe/modifie ; chaque vendeuse lit le sien
-- pour afficher sa jauge de progression dans son espace.
--
-- Securite : RLS active. Admin = gestion complete (prive.est_admin()).
-- Vendeuse = lecture de SES propres objectifs uniquement (prive.mon_profil_id()).
-- Grants explicites a authenticated ET service_role (sinon permission denied).
-- ═══════════════════════════════════════════════════════════════════════

create table if not exists public.objectifs_vendeuses (
  id          bigint generated by default as identity primary key,
  vendeuse_id bigint  not null references public.utilisateurs (id) on delete cascade,
  periode     date    not null,               -- premier jour du mois (heure locale)
  objectif    numeric not null default 0 check (objectif >= 0),
  created_at  timestamptz not null default now(),
  unique (vendeuse_id, periode)
);

alter table public.objectifs_vendeuses enable row level security;

-- Admin : gestion complete.
create policy "objectifs: admin lit"
  on public.objectifs_vendeuses for select to authenticated using (prive.est_admin());
create policy "objectifs: admin ajoute"
  on public.objectifs_vendeuses for insert to authenticated with check (prive.est_admin());
create policy "objectifs: admin modifie"
  on public.objectifs_vendeuses for update to authenticated using (prive.est_admin()) with check (prive.est_admin());
create policy "objectifs: admin supprime"
  on public.objectifs_vendeuses for delete to authenticated using (prive.est_admin());

-- Vendeuse : lit uniquement ses propres objectifs (pour sa jauge).
create policy "objectifs: la vendeuse lit le sien"
  on public.objectifs_vendeuses for select to authenticated using (vendeuse_id = prive.mon_profil_id());

grant all on public.objectifs_vendeuses to authenticated;
grant all on public.objectifs_vendeuses to service_role;
