-- ═══════════════════════════════════════════════════════════════════════
-- Notifications de vente (Web Push) — abonnements des appareils admin
--
-- Stocke les "push subscriptions" du navigateur/PWA de l'admin. L'envoi se
-- fait cote serveur avec la cle secrete (routes /api/push/subscribe et
-- /api/ventes), qui contourne RLS. Les clients n'accedent jamais a cette
-- table directement : RLS activee SANS policy = porte fermee cote client.
-- ═══════════════════════════════════════════════════════════════════════

create table if not exists public.push_subscriptions (
  id             bigint generated by default as identity primary key,
  utilisateur_id bigint not null references public.utilisateurs (id) on delete cascade,
  endpoint       text   not null unique,
  p256dh         text   not null,
  auth           text   not null,
  user_agent     text,
  created_at     timestamptz not null default now()
);

create index if not exists push_subscriptions_utilisateur_idx
  on public.push_subscriptions (utilisateur_id);

alter table public.push_subscriptions enable row level security;
-- Volontairement aucune policy : seules les routes serveur (cle secrete)
-- lisent et ecrivent. anon n'a de toute facon plus rien sur public.
revoke all on public.push_subscriptions from anon;

-- La cle secrete (role service_role) doit pouvoir lire/ecrire cette table.
-- RLS reste active sans policy pour fermer l'acces aux clients, mais le GRANT
-- de table est necessaire : sans lui, les routes serveur se prennent un
-- "permission denied" (contrairement aux tables plus anciennes, deja grantees).
grant all on public.push_subscriptions to service_role;
